const Selvagens = [
  {
    id: 1,
    nome: "Heracross",
    treinador: "",
    nature: "Bashful",
    tipo: ["Inseto", "Lutador"],
    nivel: 50,
    pontos_de_vida: 232,
    status: {
      saude: 8,
      ataque: 43,
      defesa: 8,
      atq_esp: 4,
      def_esp: 20,
      velocidade: 19,
    },
    evasao: {
      fisica: 6,
      especial: 6,
      veloz: 9,
    },
    bonus_elemental: 10,
    ataques: [
      "Megachifre",
      "Corpo a Corpo",
      "Fúria",
      "Quebra-Telha",
      "Derrubada",
      "Golpe Aéreo",
      "Agulhas",
      "Arremesso Sísmico",
    ],
    habilidades: ["Tenacidade", "Fraqueza"],
    caracteristicas: ["Escalada", "Hierarquia"],
  },
  {
    id: 2,
    nome: "Milotic",
    treinador: "",
    nature: "Naive",
    tipo: ["Água"],
    nivel: 50,
    pontos_de_vida: 280,
    status: {
      saude: 20,
      ataque: 6,
      defesa: 8,
      atq_esp: 40,
      def_esp: 11,
      velocidade: 20,
    },
    evasao: {
      fisica: 5,
      especial: 6,
      veloz: 9,
    },
    bonus_elemental: 10,
    ataques: [
      "Cauda de Água",
      "Cauda do Dragão",
      "Hidrobomba",
      "Pulso d'Água",
      "Salvaguarda",
      "Dança da Chuva",
      "Nevoeiro",
      null,
    ],
    habilidades: ["Obtusidade", "Tentação"],
    caracteristicas: ["Guelras"],
  },
  {
    id: 3,
    nome: "Bisharp",
    treinador: "",
    nature: "Desesperado",
    tipo: ["Dark", "Metal"],
    nivel: 50,
    pontos_de_vida: 240,
    status: {
      saude: 10,
      ataque: 45,
      defesa: 15,
      atq_esp: 6,
      def_esp: 12,
      velocidade: 12,
    },
    evasao: {
      fisica: 7,
      especial: 5,
      veloz: 6,
    },
    bonus_elemental: 10,
    ataques: [
      "Retalhar",
      "Metalizar Garra",
      "Cabeça de Ferro",
      "Confisco",
      "Corte Psíquico",
      "Garantia",
      "Ruído",
      "Defesa de Ferro",
    ],
    habilidades: ["Foco Interior", "Pressão"],
    caracteristicas: ["Aura", "Faro", "Hierarquia", "Silêncio"],
  },
  {
    id: 4,
    nome: "Houndoom",
    treinador: "",
    nature: "Bold",
    tipo: ["Dark", "Fogo"],
    nivel: 50,
    pontos_de_vida: 252,
    status: {
      saude: 13,
      ataque: 7,
      defesa: 7,
      atq_esp: 41,
      def_esp: 13,
      velocidade: 20,
    },
    evasao: {
      fisica: 2,
      especial: 5,
      veloz: 7,
    },
    bonus_elemental: 10,
    ataques: [
      "Lança-Chamas",
      "Mordida",
      "Presa de Fogo",
      "Fogo-Fátuo",
      "Espancamento",
      "Confisco",
      "Trapaça",
      "Farejar",
    ],
    habilidades: ["Madrugar", "Tensão"],
    caracteristicas: ["Faro "],
  },
  {
    id: 5,
    nome: "Drapion",
    treinador: "",
    nature: "Excêntrico",
    tipo: ["Dark", "Veneno"],
    nivel: 50,
    pontos_de_vida: 264,
    status: {
      saude: 16,
      ataque: 15,
      defesa: 29,
      atq_esp: 3,
      def_esp: 4,
      velocidade: 17,
    },
    evasao: {
      fisica: 8,
      especial: 4,
      veloz: 5,
    },
    bonus_elemental: 10,
    ataques: [
      "Presa Venenosa",
      "Espinhos Tóxicos",
      "Venochoque",
      "Agulhas Gêmeas",
      "Afiar",
      "Emboscada",
      "Careta",
      "Picada",
    ],
    habilidades: ["Franco-Atirador", "Visão Aguçada"],
    caracteristicas: ["Faro "],
  }
];
export default Selvagens;
